version: '3.8'

services:
  kavida-app:
    image: kavida-app:v1
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - TENANT_ID=${TENANT_ID}
      - USER_EMAIL=${USER_EMAIL}
      - MS_GRAPH_API_URL=${MS_GRAPH_API_URL}
      - MS_GRAPH_AUTH_URL=${MS_GRAPH_AUTH_URL}
      - SCOPES=${SCOPES}
      - MONGO_AUTH_USERNAME=${MONGO_AUTH_USERNAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - MONGO_AUTH_PASSWORD=${MONGO_AUTH_PASSWORD}
      - MONGO_SERVER_ADDRESS=mongodb
      - MONGO_SERVER_PORT=${MONGO_SERVER_PORT}
      - API_V1_STR=${API_V1_STR}
      - PROJECT_NAME=${PROJECT_NAME}

    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password123
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 